name: Publish to VS Code Marketplace and Open VSX

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v0.0.2, v1.0.0, etc.
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # This gives the workflow permission to create releases

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce and ovsx
        run: |
          npm install -g @vscode/vsce
          npm install -g ovsx

      - name: Package Extension
        run: vsce package

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish -p $VSCE_PAT

      - name: Publish to Open VSX
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: ovsx publish -p $OVSX_PAT

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}