name: Test Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'
        
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate theme generation
      run: |
        python generate_theme.py color_palettes/fedaykin-dark.json
        python generate_theme.py color_palettes/fedaykin-dark-arrakis.json
        
    - name: Package Extension
      run: vsce package
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: fedaykin-themes-vsix
        path: '*.vsix'